### ISSUE TITLE
Include SASL functionality in a new release

### ISSUE THREAD

**Issue by begriffs** [fstd/libsrsirc#3]
I noticed the most recent release (0.0.14) is missing some functions on the master branch like `irc_set_sasl` and `lsi_ut_sasl_mkplauth`. Could you create a new release please?

**Comment by fstd** [comment]
Hi, sorry for not getting back to you earlier.

0.0.14 did not support SASL yet, so that's why those functions aren't included.  Unfortunately there's a couple loose ends right now so I don't feel like making a new release.

Please use the devel branch instead, at least for now.  It's stable.  If SASL turns out not to work in the devel branch, please tell me about it.
